version: "3.5"
services:
  dimensional-dbt:
    image: dimensional_dbt
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test-dimensional-dbt:/app
      - ./macros:/dimensional-dbt/macros
      - ./dbt_project.yml/dimensional-dbt/dbt_project.yml
    entrypoint: ["./entrypoint.sh"]
    env_file:
      - .env
    environment:
      - DBT_PROFILES_DIR=/app
    ports:
      - "8080:8080"