version: "3.5"
services:
  dimensional_dbt:
    image: dimensional_dbt
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - DBT_PROFILES_DIR=/app
    ports:
      - "8080:8080"