version: "3.5"
services:
  dimensional_dbt:
    image: dimensional_dbt
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test_dimensional_dbt:/app
      - ./macros:/dimensional_dbt/macros
      - ./dbt_project.yml:/dimensional_dbt/dbt_project.yml
    working_dir: /app
    entrypoint: ["./entrypoint.sh"]
    env_file:
      - .env
    environment:
      - DBT_PROFILES_DIR=/app
    ports:
      - "8080:8080"