version: 2

sources:
  - name: snapshots
    schema: DIMENSIONAL_DBT_SNAPSHOTS
    tables:
      - name: bluth_stripe_banana_stand_product
      - name: bluth_stripe_order_events
      - name: bluth_wms_inventory
      - name: chiquita_invoices

  - name: tests
    schema: DIMENSIONAL_DBT_SNAPSHOTS
    tables:
      - name: expected_stripe_snapshots_truncated_by_hour
      - name: expected_stripe_snapshots_truncated_by_day